select sph.sy_from, sph.school_id, 

-- Drought
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) djan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) dfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) dmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) dapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) dmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) djun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) djul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) daug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) dsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) doct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) dnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1352)),0)) ddec,

-- Earthquake 
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) ejan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) efeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) emar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) eapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) emay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) ejun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) ejul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) eaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) esep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) eoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) enov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 522)),0)) edec,

-- Fire
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fijan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fifeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fimar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fiapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fimay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fijun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fijul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fiaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fisep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fioct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) finov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1353)),0)) fidec,

-- Flood
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) fjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) ffeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) fmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) fapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) fmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) fjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) fjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) faug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) fsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) foct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) fnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 521)),0)) fdec,

-- Landslide
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) ljan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) lfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) lmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) lapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) lmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) ljun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) ljul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) laug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) lsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) loct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) lnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 523)),0)) ldec,

-- Storm Surge
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) sssep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1351)),0)) ssdec,

-- Tropical Cyclone
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1350)),0)) tcdec,

-- Tsunami
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) tjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) tfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) tmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) tapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) tmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) tjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) tjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) taug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) tsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) toct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) tnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 524)),0)) tdec,

-- Volcanic Eruption
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) vejan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) vefeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) vemar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) veapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) vemay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) vejun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) vejul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) veaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) vesep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) veoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) venov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 525)),0)) vedec,


-- Armed Conflict
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 527)),0)) acdec,

-- Crime Against School Head/s
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 638)),0)) cshdec,

-- Crime Against School Property
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1360)),0)) cspdec,

-- Crime Against Students
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) cssep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1358)),0)) csdec,

-- Crime Against Teachers
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1359)),0)) ctdec,

-- Fire (Electrical Wiring Failure)
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 528)),0)) firdec,

-- Health Threat
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1357)),0)) htdec,

-- Oil Spill
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) ossep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1355)),0)) osdec,

-- Security Threat
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1356)),0)) secdec,

-- Structural Collapse
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1354)),0)) scdec,

-- Others
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS ojan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS ofeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS omar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS oapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS omay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS ojun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS ojul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS oaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS osep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS ooct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS onov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529)),0)) AS odec,
(select (y.others) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 529) AS others,


-- School Used as Evacuation Center
(ifnull(sum((select sum(y.dc_jan) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecjan,
(ifnull(sum((select sum(y.dc_feb) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecfeb,
(ifnull(sum((select sum(y.dc_mar) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecmar,
(ifnull(sum((select sum(y.dc_apr) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecapr,
(ifnull(sum((select sum(y.dc_may) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecmay,
(ifnull(sum((select sum(y.dc_jun) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecjun,
(ifnull(sum((select sum(y.dc_jul) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecjul,
(ifnull(sum((select sum(y.dc_aug) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecaug,
(ifnull(sum((select sum(y.dc_sep) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecsep,
(ifnull(sum((select sum(y.dc_oct) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecoct,
(ifnull(sum((select sum(y.dc_nov) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecnov,
(ifnull(sum((select sum(y.dc_dec) from ebeisdb.disaster_calamities y where y.report_history_id = rh.id and y.discal_item_id = 1362)),0)) ecdec,


-- Vulnerabilities
(select (z.vulnerabilities01) from ebeisdb.other_school_data z where z.report_history_id = rh.id) AS vulnerability01,
(select (z.vulnerabilities02) from ebeisdb.other_school_data z where z.report_history_id = rh.id) AS vulnerability02,
(select (z.vulnerabilities03) from ebeisdb.other_school_data z where z.report_history_id = rh.id) AS vulnerability03

from ebeisdb.school_profile_history sph
LEFT JOIN ebeisdb.ref_region rg on (rg.id = sph.region_id)
LEFT JOIN ebeisdb.report_history rh on (rh.school_id = sph.school_id and rh.sy_from = sph.sy_from 
 and rh.report_id = if(sph.general_classification_id = 7, if(sph.co_gen_class=433, if(sph.sy_from=2016, 24, 1), if(sph.sy_from=2016, 26, 2)),
 if(sph.co_gen_class=433, if(sph.sy_from=2016, 22, 3), if(sph.sy_from=2016, 23, 4))) and rh.report_status > 300) 
where sph.sy_from = 2016 and sph.take_part_id in (1,2,3)
GROUP BY sph.sy_from, sph.school_id
ORDER BY sph.sy_from, rg.rank ASC, sph.school_id ASC

INTO OUTFILE '/var/tmp/calamitiesvul.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

