SELECT sph.sy_from, sph.school_id

-- TLE - Home Economics
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=671)),0) as g9male_beautycare
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=671)),0) as g9female_beautycare
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=671)),0) as g9tot_beautycare
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=671)),0) as g10male_beautycare
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=671)),0) as g10female_beautycare
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=671)),0) as g10tot_beautycare
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=671)),0) as gtotmale_beautycare
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=671)),0) as gtotfemale_beautycare
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=671)),0) as gtot_beautycare

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=672)),0) as g9male_caregiving
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=672)),0) as g9female_caregiving
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=672)),0) as g9tot_caregiving
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=672)),0) as g10male_caregiving
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=672)),0) as g10female_caregiving
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=672)),0) as g10tot_caregiving
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=672)),0) as gtotmale_caregiving
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=672)),0) as gtotfemale_caregiving
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=672)),0) as gtot_caregiving

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=673)),0) as g9male_cookery
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=673)),0) as g9female_cookery
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=673)),0) as g9tot_cookery
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=673)),0) as g10male_cookery
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=673)),0) as g10female_cookery
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=673)),0) as g10tot_cookery
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=673)),0) as gtotmale_cookery
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=673)),0) as gtotfemale_cookery
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=673)),0) as gtot_cookery

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=674)),0) as g9male_dressmaking
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=674)),0) as g9female_dressmaking
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=674)),0) as g9tot_dressmaking
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=674)),0) as g10male_dressmaking
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=674)),0) as g10female_dressmaking
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=674)),0) as g10tot_dressmaking
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=674)),0) as gtotmale_dressmaking
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=674)),0) as gtotfemale_dressmaking
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=674)),0) as gtot_dressmaking

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=676)),0) as g9male_frontoffice
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=676)),0) as g9female_frontoffice
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=676)),0) as g9tot_frontoffice
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=676)),0) as g10male_frontoffice
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=676)),0) as g10female_frontoffice
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=676)),0) as g10tot_frontoffice
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=676)),0) as gtotmale_frontoffice
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=676)),0) as gtotfemale_frontoffice
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=676)),0) as gtot_frontoffice

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=677)),0) as g9male_handicraft
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=677)),0) as g9female_handicraft
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=677)),0) as g9tot_handicraft
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=677)),0) as g10male_handicraft
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=677)),0) as g10female_handicraft
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=677)),0) as g10tot_handicraft
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=677)),0) as gtotmale_handicraft
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=677)),0) as gtotfemale_handicraft
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=677)),0) as gtot_handicraft

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=678)),0) as g9male_household
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=678)),0) as g9female_household
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=678)),0) as g9tot_household
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=678)),0) as g10male_household
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=678)),0) as g10female_household
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=678)),0) as g10tot_household
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=678)),0) as gtotmale_household
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=678)),0) as gtotfemale_household
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=678)),0) as gtot_household

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=679)),0) as g9male_travel
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=679)),0) as g9female_travel
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=679)),0) as g9tot_travel
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=679)),0) as g10male_travel
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=679)),0) as g10female_travel
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=679)),0) as g10tot_travel
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=679)),0) as gtotmale_travel
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=679)),0) as gtotfemale_travel
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=679)),0) as gtot_travel

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=681)),0) as g9male_wellness
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=681)),0) as g9female_wellness
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=681)),0) as g9tot_wellness
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=681)),0) as g10male_wellness
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=681)),0) as g10female_wellness
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=681)),0) as g10tot_wellness
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=681)),0) as gtotmale_wellness
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=681)),0) as gtotfemale_wellness
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=681)),0) as gtot_wellness

-- TLE - Agri-Fishery Arts
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=682)),0) as g9male_agricrop
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=682)),0) as g9female_agricrop
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=682)),0) as g9tot_agricrop
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=682)),0) as g10male_agricrop
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=682)),0) as g10female_agricrop
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=682)),0) as g10tot_agricrop
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=682)),0) as gtotmale_agricrop
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=682)),0) as gtotfemale_agricrop
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=682)),0) as gtot_agricrop

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=684)),0) as g9male_animal
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=684)),0) as g9female_animal
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=684)),0) as g9tot_animal
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=684)),0) as g10male_animal
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=684)),0) as g10female_animal
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=684)),0) as g10tot_animal
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=684)),0) as gtotmale_animal
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=684)),0) as gtotfemale_animal
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=684)),0) as gtot_animal

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=686)),0) as g9male_aquaculture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=686)),0) as g9female_aquaculture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=686)),0) as g9tot_aquaculture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=686)),0) as g10male_aquaculture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=686)),0) as g10female_aquaculture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=686)),0) as g10tot_aquaculture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=686)),0) as gtotmale_aquaculture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=686)),0) as gtotfemale_aquaculture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=686)),0) as gtot_aquaculture

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=687)),0) as g9male_fishprocessing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=687)),0) as g9female_fishprocessing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=687)),0) as g9tot_fishprocessing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=687)),0) as g10male_fishprocessing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=687)),0) as g10female_fishprocessing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=687)),0) as g10tot_fishprocessing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=687)),0) as gtotmale_fishprocessing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=687)),0) as gtotfemale_fishprocessing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=687)),0) as gtot_fishprocessing

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=688)),0) as g9male_horticulture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=688)),0) as g9female_horticulture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=688)),0) as g9tot_horticulture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=688)),0) as g10male_horticulture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=688)),0) as g10female_horticulture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=688)),0) as g10tot_horticulture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=688)),0) as gtotmale_horticulture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=688)),0) as gtotfemale_horticulture
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=688)),0) as gtot_horticulture

-- TLE - Industrial Arts
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=690)),0) as g9male_automotive
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=690)),0) as g9female_automotive
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=690)),0) as g9tot_automotive
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=690)),0) as g10male_automotive
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=690)),0) as g10female_automotive
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=690)),0) as g10tot_automotive
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=690)),0) as gtotmale_automotive
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=690)),0) as gtotfemale_automotive
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=690)),0) as gtot_automotive

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=691)),0) as g9male_carpentry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=691)),0) as g9female_carpentry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=691)),0) as g9tot_carpentry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=691)),0) as g10male_carpentry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=691)),0) as g10female_carpentry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=691)),0) as g10tot_carpentry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=691)),0) as gtotmale_carpentry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=691)),0) as gtotfemale_carpentry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=691)),0) as gtot_carpentry

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=692)),0) as g9male_electronics
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=692)),0) as g9female_electronics
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=692)),0) as g9tot_electronics
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=692)),0) as g10male_electronics
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=692)),0) as g10female_electronics
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=692)),0) as g10tot_electronics
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=692)),0) as gtotmale_electronics
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=692)),0) as gtotfemale_electronics
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=692)),0) as gtot_electronics

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=693)),0) as g9male_electrical
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=693)),0) as g9female_electrical
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=693)),0) as g9tot_electrical
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=693)),0) as g10male_electrical
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=693)),0) as g10female_electrical
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=693)),0) as g10tot_electrical
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=693)),0) as gtotmale_electrical
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=693)),0) as gtotfemale_electrical
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=693)),0) as gtot_electrical

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=694)),0) as g9male_masonry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=694)),0) as g9female_masonry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=694)),0) as g9tot_masonry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=694)),0) as g10male_masonry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=694)),0) as g10female_masonry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=694)),0) as g10tot_masonry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=694)),0) as gtotmale_masonry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=694)),0) as gtotfemale_masonry
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=694)),0) as gtot_masonry

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=695)),0) as g9male_plumbing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=695)),0) as g9female_plumbing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=695)),0) as g9tot_plumbing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=695)),0) as g10male_plumbing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=695)),0) as g10female_plumbing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=695)),0) as g10tot_plumbing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=695)),0) as gtotmale_plumbing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=695)),0) as gtotfemale_plumbing
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=695)),0) as gtot_plumbing

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=696)),0) as g9male_refrigeration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=696)),0) as g9female_refrigeration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=696)),0) as g9tot_refrigeration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=696)),0) as g10male_refrigeration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=696)),0) as g10female_refrigeration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=696)),0) as g10tot_refrigeration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=696)),0) as gtotmale_refrigeration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=696)),0) as gtotfemale_refrigeration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=696)),0) as gtot_refrigeration

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=697)),0) as g9male_welding
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=697)),0) as g9female_welding
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=697)),0) as g9tot_welding
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=697)),0) as g10male_welding
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=697)),0) as g10female_welding
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=697)),0) as g10tot_welding
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=697)),0) as gtotmale_welding
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=697)),0) as gtotfemale_welding
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=697)),0) as gtot_welding

-- TLE - ICT
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=699)),0) as g9male_computerhardware
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=699)),0) as g9female_computerhardware
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=699)),0) as g9tot_computerhardware
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=699)),0) as g10male_computerhardware
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=699)),0) as g10female_computerhardware
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=699)),0) as g10tot_computerhardware
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=699)),0) as gtotmale_computerhardware
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=699)),0) as gtotfemale_computerhardware
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=699)),0) as gtot_computerhardware

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=701)),0) as g9male_contactcenter
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=701)),0) as g9female_contactcenter
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=701)),0) as g9tot_contactcenter
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=701)),0) as g10male_contactcenter
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=701)),0) as g10female_contactcenter
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=701)),0) as g10tot_contactcenter
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=701)),0) as gtotmale_contactcenter
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=701)),0) as gtotfemale_contactcenter
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=701)),0) as gtot_contactcenter

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=702)),0) as g9male_illustration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=702)),0) as g9female_illustration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=702)),0) as g9tot_illustration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=702)),0) as g10male_illustration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=702)),0) as g10female_illustration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=702)),0) as g10tot_illustration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=702)),0) as gtotmale_illustration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=702)),0) as gtotfemale_illustration
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=702)),0) as gtot_illustration

	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=703)),0) as g9male_drafting
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=703)),0) as g9female_drafting
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 107 AND ep.program_id=339 AND ep.programs_offered_id=703)),0) as g9tot_drafting
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=703)),0) as g10male_drafting
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=703)),0) as g10female_drafting
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.grade_level_id = 108 AND ep.program_id=339 AND ep.programs_offered_id=703)),0) as g10tot_drafting
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=703)),0) as gtotmale_drafting
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=703)),0) as gtotfemale_drafting
	, IFNULL(SUM((SELECT SUM(IFNULL(ep.enrolled_male,0)+IFNULL(ep.enrolled_female,0)) AS sum_ep FROM ebeisdb.enrollment_program_summary ep WHERE ep.report_history_id = rh.id AND ep.category_id=434 AND ep.program_id=339 AND ep.programs_offered_id=703)),0) as gtot_drafting

FROM ebeisdb.school_profile_history sph
   LEFT JOIN ebeisdb.ref_region rr ON (rr.id=sph.region_id)
   LEFT JOIN (ebeisdb.report_history rh 
	      inner join ebeisdb.ref_report_history rrh on rh.ref_report_history_id = rrh.id
	      inner join ebeisdb.ref_reports rrs on rrs.id  = rrh.report_id
	      inner join ebeisdb.ref_report_generics rrg on rrg.id = rrs.ref_report_generics_id and rrg.id=1
	 ) on rh.school_id = sph.school_id and rh.sy_from= sph.sy_from and rh.report_status > 300 -- cast( sph.sy_from as unsigned)
   WHERE  sph.take_part_id IN (1,2,3) and sph.general_classification_id = 7 and sph.co_gen_class = 434 and sph.sy_from =2016
   GROUP BY rh.sy_from, sph.SCHOOL_ID 
   ORDER BY sph.SY_FROM, rr.RANK ASC, sph.SCHOOL_ID ASC

INTO OUTFILE '/var/tmp/tle.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';
