ALTER TABLE orsdb.sped
ADD g7male_dc smallint DEFAULT 0,
ADD g7female_dc smallint DEFAULT 0,
ADD g7total_dc smallint DEFAULT 0,
ADD g8male_dc smallint DEFAULT 0,
ADD g8female_dc smallint DEFAULT 0,
ADD g8total_dc smallint DEFAULT 0,
ADD g9male_dc smallint DEFAULT 0,
ADD g9female_dc smallint DEFAULT 0,
ADD g9total_dc smallint DEFAULT 0,
ADD g10male_dc smallint DEFAULT 0,
ADD g10female_dc smallint DEFAULT 0,
ADD g10total_dc smallint DEFAULT 0,
ADD g11male_dc smallint DEFAULT 0,
ADD g11female_dc smallint DEFAULT 0,
ADD g11total_dc smallint DEFAULT 0,
ADD g12male_dc smallint DEFAULT 0,
ADD g12female_dc smallint DEFAULT 0,
ADD g12total_dc smallint DEFAULT 0,
ADD ngmale_dc smallint DEFAULT 0,
ADD ngfemale_dc smallint DEFAULT 0,
ADD ngtotal_dc smallint DEFAULT 0,
ADD totmale_dc smallint DEFAULT 0,
ADD totfemale_dc smallint DEFAULT 0,
ADD total_dc smallint DEFAULT 0;

