ALTER TABLE orsdb.sped
ADD g7male_ds smallint DEFAULT 0,
ADD g7female_ds smallint DEFAULT 0,
ADD g7total_ds smallint DEFAULT 0,
ADD g8male_ds smallint DEFAULT 0,
ADD g8female_ds smallint DEFAULT 0,
ADD g8total_ds smallint DEFAULT 0,
ADD g9male_ds smallint DEFAULT 0,
ADD g9female_ds smallint DEFAULT 0,
ADD g9total_ds smallint DEFAULT 0,
ADD g10male_ds smallint DEFAULT 0,
ADD g10female_ds smallint DEFAULT 0,
ADD g10total_ds smallint DEFAULT 0,
ADD g11male_ds smallint DEFAULT 0,
ADD g11female_ds smallint DEFAULT 0,
ADD g11total_ds smallint DEFAULT 0,
ADD g12male_ds smallint DEFAULT 0,
ADD g12female_ds smallint DEFAULT 0,
ADD g12total_ds smallint DEFAULT 0,
ADD ngmale_ds smallint DEFAULT 0,
ADD ngfemale_ds smallint DEFAULT 0,
ADD ngtotal_ds smallint DEFAULT 0,
ADD totmale_ds smallint DEFAULT 0,
ADD totfemale_ds smallint DEFAULT 0,
ADD total_ds smallint DEFAULT 0;

