ALTER TABLE orsdb.sped
ADD g7male_dwcg smallint DEFAULT 0,
ADD g7female_dwcg smallint DEFAULT 0,
ADD g7total_dwcg smallint DEFAULT 0,
ADD g8male_dwcg smallint DEFAULT 0,
ADD g8female_dwcg smallint DEFAULT 0,
ADD g8total_dwcg smallint DEFAULT 0,
ADD g9male_dwcg smallint DEFAULT 0,
ADD g9female_dwcg smallint DEFAULT 0,
ADD g9total_dwcg smallint DEFAULT 0,
ADD g10male_dwcg smallint DEFAULT 0,
ADD g10female_dwcg smallint DEFAULT 0,
ADD g10total_dwcg smallint DEFAULT 0,
ADD g11male_dwcg smallint DEFAULT 0,
ADD g11female_dwcg smallint DEFAULT 0,
ADD g11total_dwcg smallint DEFAULT 0,
ADD g12male_dwcg smallint DEFAULT 0,
ADD g12female_dwcg smallint DEFAULT 0,
ADD g12total_dwcg smallint DEFAULT 0,
ADD ngmale_dwcg smallint DEFAULT 0,
ADD ngfemale_dwcg smallint DEFAULT 0,
ADD ngtotal_dwcg smallint DEFAULT 0,
ADD totmale_dwcg smallint DEFAULT 0,
ADD totfemale_dwcg smallint DEFAULT 0,
ADD total_dwcg smallint DEFAULT 0;

