ALTER TABLE orsdb.sped
ADD g7male_dh smallint DEFAULT 0,
ADD g7female_dh smallint DEFAULT 0,
ADD g7total_dh smallint DEFAULT 0,
ADD g8male_dh smallint DEFAULT 0,
ADD g8female_dh smallint DEFAULT 0,
ADD g8total_dh smallint DEFAULT 0,
ADD g9male_dh smallint DEFAULT 0,
ADD g9female_dh smallint DEFAULT 0,
ADD g9total_dh smallint DEFAULT 0,
ADD g10male_dh smallint DEFAULT 0,
ADD g10female_dh smallint DEFAULT 0,
ADD g10total_dh smallint DEFAULT 0,
ADD g11male_dh smallint DEFAULT 0,
ADD g11female_dh smallint DEFAULT 0,
ADD g11total_dh smallint DEFAULT 0,
ADD g12male_dh smallint DEFAULT 0,
ADD g12female_dh smallint DEFAULT 0,
ADD g12total_dh smallint DEFAULT 0,
ADD ngmale_dh smallint DEFAULT 0,
ADD ngfemale_dh smallint DEFAULT 0,
ADD ngtotal_dh smallint DEFAULT 0,
ADD totmale_dh smallint DEFAULT 0,
ADD totfemale_dh smallint DEFAULT 0,
ADD total_dh smallint DEFAULT 0;

