ALTER TABLE orsdb.sped
ADD g7male_drcpu smallint DEFAULT 0,
ADD g7female_drcpu smallint DEFAULT 0,
ADD g7total_drcpu smallint DEFAULT 0,
ADD g8male_drcpu smallint DEFAULT 0,
ADD g8female_drcpu smallint DEFAULT 0,
ADD g8total_drcpu smallint DEFAULT 0,
ADD g9male_drcpu smallint DEFAULT 0,
ADD g9female_drcpu smallint DEFAULT 0,
ADD g9total_drcpu smallint DEFAULT 0,
ADD g10male_drcpu smallint DEFAULT 0,
ADD g10female_drcpu smallint DEFAULT 0,
ADD g10total_drcpu smallint DEFAULT 0,
ADD g11male_drcpu smallint DEFAULT 0,
ADD g11female_drcpu smallint DEFAULT 0,
ADD g11total_drcpu smallint DEFAULT 0,
ADD g12male_drcpu smallint DEFAULT 0,
ADD g12female_drcpu smallint DEFAULT 0,
ADD g12total_drcpu smallint DEFAULT 0,
ADD ngmale_drcpu smallint DEFAULT 0,
ADD ngfemale_drcpu smallint DEFAULT 0,
ADD ngtotal_drcpu smallint DEFAULT 0,
ADD totmale_drcpu smallint DEFAULT 0,
ADD totfemale_drcpu smallint DEFAULT 0,
ADD total_drcpu smallint DEFAULT 0;

