ALTER TABLE orsdb.personnel_nonteaching
ADD `ap_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0' AFTER p_plantilla,
ADD  `ap_actual_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_actual_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_total_actualmf` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `ap_onleave` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_vacant` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_detailed_office` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `ap_detailed_within` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_detailed_outside` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_detailed_school` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_detailedto_total` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_total_school_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_detailed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_detailed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_total_detailed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_borrowed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_borrowed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_total_borrowed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_nf_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_nf_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ap_total_nf` smallint(5) unsigned NOT NULL DEFAULT '0',

ADD `nrs_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0' ,
ADD  `nrs_actual_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_actual_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_total_actualmf` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `nrs_onleave` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_vacant` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_detailed_office` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `nrs_detailed_within` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_detailed_outside` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_detailed_school` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_detailedto_total` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_total_school_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_detailed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_detailed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_total_detailed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_borrowed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_borrowed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_total_borrowed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_nf_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_nf_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `nrs_total_nf` smallint(5) unsigned NOT NULL DEFAULT '0',

ADD `reg_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0' ,
ADD  `reg_actual_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_actual_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_total_actualmf` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `reg_onleave` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_vacant` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_detailed_office` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `reg_detailed_within` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_detailed_outside` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_detailed_school` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_detailedto_total` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_total_school_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_detailed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_detailed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_total_detailed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_borrowed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_borrowed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_total_borrowed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_nf_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_nf_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `reg_total_nf` smallint(5) unsigned NOT NULL DEFAULT '0',

ADD `ao_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0' ,
ADD  `ao_actual_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_actual_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_total_actualmf` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `ao_onleave` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_vacant` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_detailed_office` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `ao_detailed_within` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_detailed_outside` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_detailed_school` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_detailedto_total` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_total_school_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_detailed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_detailed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_total_detailed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_borrowed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_borrowed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_total_borrowed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_nf_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_nf_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `ao_total_nf` smallint(5) unsigned NOT NULL DEFAULT '0',

ADD `aa_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0' ,
ADD  `aa_actual_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_actual_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_total_actualmf` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `aa_onleave` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_vacant` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_detailed_office` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `aa_detailed_within` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_detailed_outside` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_detailed_school` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_detailedto_total` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_total_school_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_detailed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_detailed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_total_detailed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_borrowed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_borrowed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_total_borrowed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_nf_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_nf_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `aa_total_nf` smallint(5) unsigned NOT NULL DEFAULT '0',

ADD `pdo1_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0' ,
ADD  `pdo1_actual_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_actual_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_total_actualmf` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `pdo1_onleave` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_vacant` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_detailed_office` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `pdo1_detailed_within` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_detailed_outside` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_detailed_school` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_detailedto_total` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_total_school_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_detailed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_detailed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_total_detailed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_borrowed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_borrowed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_total_borrowed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_nf_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_nf_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo1_total_nf` smallint(5) unsigned NOT NULL DEFAULT '0',

ADD `pdo2_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0' ,
ADD  `pdo2_actual_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_actual_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_total_actualmf` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `pdo2_onleave` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_vacant` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_detailed_office` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD `pdo2_detailed_within` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_detailed_outside` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_detailed_school` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_detailedto_total` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_total_school_plantilla` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_detailed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_detailed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_total_detailed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_borrowed_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_borrowed_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_total_borrowed` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_nf_male` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_nf_female` smallint(5) unsigned NOT NULL DEFAULT '0',
ADD  `pdo2_total_nf` smallint(5) unsigned NOT NULL DEFAULT '0'

